version: '2'

services:
  n3uron:
    build: .
    ports:
      - 8003:8003 # HTTP WebUI
      - 8443:8443 # HTTPS WebUI
      - 8004:8004 # HTTP WebVision
      - 8444:8444 # HTTPS WebVision
      - 3001:3001 # Inbound Links
    volumes:
      - n3_config:/opt/n3uron/config
      - n3_data:/opt/n3uron/data
      - n3_licenses:/opt/n3uron/licenses
      - n3_log:/opt/n3uron/log
    restart: always

  mqtt:
    image: eclipse-mosquitto:1.6
    ports:
      - 1883:1883
    restart: always

  telegraf:
    image: telegraf:1.26
    entrypoint: >
      sh -c "echo '[[outputs.influxdb_v2]]\nurls = [\"http://influxdb:8086\"]\ntoken = \"$DOCKER_INFLUXDB_INIT_ADMIN_TOKEN\"\norganization = \"N3uron\"\nbucket = \"demo\"\n[[inputs.mqtt_consumer]]\nservers = [\"tcp://mqtt:1883\"]\ntopics = [\"N3URON/BLUELAKE/\"]\ndata_format = \"influx\"' >> /etc/telegraf/telegraf.conf && telegraf --config /etc/telegraf/telegraf.conf"
    restart: always

  influxdb:
    image: influxdb:2.7
    ports:
      - 8086:8086
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
    volumes:
      - influx_config:/etc/influxdb2
      - influx_data:/var/lib/influxdb2
    restart: always

  grafana:
    image: grafana/grafana-oss:9.5.2
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    restart: always

volumes:
  n3_config:
  n3_data:
  n3_licenses:
  n3_log:
  influx_config:
  influx_data:
  grafana_data:
